"""
Phase 16: Multi-Region Prediction Service
==========================================
Wraps the Phase 15 trained model (models/multi_region/) to provide
location-based prospectivity predictions for the 6 supported Indian
manganese belts.

Design contract:
  - Phase 15 model artifacts are loaded READ-ONLY. This module never
    retrains or overwrites them.
  - Coordinates that fall inside a supported region bbox get a
    geology-calibrated feature synthesis and a prediction.
  - Coordinates outside all supported regions return
    is_validated_region=False with a clear message. No exception is raised.
  - Feature synthesis uses the same spectral distributions as
    multi_region_trainer.py (_spectral_signature logic), parameterised
    by proximity to known deposits — not random noise.
  - No live satellite imagery or DEM data is fetched at inference time.
"""

import os
import json
import joblib
import numpy as np
import pandas as pd
from typing import Any, Dict, List, Optional, Tuple

try:
    from app.ml.multi_region_trainer import (
        MANGANESE_REGIONS,
        FEATURE_COLUMNS,
        _haversine,
        _proximity_label,
    )
except ImportError:
    from ml.multi_region_trainer import (
        MANGANESE_REGIONS,
        FEATURE_COLUMNS,
        _haversine,
        _proximity_label,
    )


# ---------------------------------------------------------------------------
# Region-calibrated spectral medians
# These are the **midpoints** of the ranges used in _spectral_signature().
# Using medians instead of random values makes predictions deterministic
# (same coord always returns the same result) and avoids misleading variance.
# ---------------------------------------------------------------------------

_SPECTRAL_MEDIANS: Dict[str, Dict[str, float]] = {
    "High": {
        "NDVI": 0.15,   # Midpoint of [0.05, 0.25]
        "B2":   0.11,   # [0.08, 0.14]
        "B3":   0.125,  # [0.09, 0.16]
        "B4":   0.175,  # [0.13, 0.22] — elevated red: iron oxide signature
        "B8":   0.15,   # [0.10, 0.20]
        "B11":  0.25,   # [0.18, 0.32] — SWIR: mineral indicator
        "B12":  0.21,   # [0.14, 0.28]
    },
    "Medium": {
        "NDVI": 0.325,  # [0.20, 0.45]
        "B2":   0.09,   # [0.06, 0.12]
        "B3":   0.11,   # [0.08, 0.14]
        "B4":   0.12,   # [0.08, 0.16]
        "B8":   0.265,  # [0.18, 0.35]
        "B11":  0.16,   # [0.10, 0.22]
        "B12":  0.13,   # [0.08, 0.18]
    },
    "Low": {
        "NDVI": 0.575,  # [0.40, 0.75]
        "B2":   0.065,  # [0.04, 0.09]
        "B3":   0.085,  # [0.06, 0.11]
        "B4":   0.08,   # [0.05, 0.11]
        "B8":   0.425,  # [0.30, 0.55]
        "B11":  0.10,   # [0.05, 0.15]
        "B12":  0.08,   # [0.04, 0.12]
    },
}

# Elevation and slope medians per label (from training data generation)
_TERRAIN_MEDIANS: Dict[str, Dict[str, float]] = {
    "High":   {"elevation": 550.0, "slope": 12.0},
    "Medium": {"elevation": 400.0, "slope": 7.0},
    "Low":    {"elevation": 250.0, "slope": 4.0},
}

# Disclaimer text included in every response
_DISCLAIMER = (
    "ManganEX predictions are generated by a machine-learning model trained "
    "on synthetic geologically-calibrated data. They do NOT confirm the "
    "presence of mineral deposits. The model has not been independently "
    "validated by geological survey data. These results are for "
    "research/demonstration purposes only and must not be used for "
    "economic, regulatory, or mining planning decisions."
)


# ---------------------------------------------------------------------------
# MultiRegionPredictor
# ---------------------------------------------------------------------------

class MultiRegionPredictor:
    """
    Phase 16 prediction service using the Phase 15 multi-region RF model.

    Parameters
    ----------
    model_dir : str
        Path to the root models directory (typically backend/../models/).
        Looks for artifacts in <model_dir>/multi_region/.
    """

    def __init__(self, model_dir: str):
        self.model_dir = model_dir
        self.mr_dir = os.path.join(model_dir, "multi_region")
        self.model = None
        self.preprocessor = None
        self.feature_importances = []
        self.metadata: Dict[str, Any] = {}
        self._load_artifacts()

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    def _load_artifacts(self):
        """Loads the Phase 15 model, preprocessor, and metadata."""
        model_path = os.path.join(self.mr_dir, "mr_model.joblib")
        prep_path = os.path.join(self.mr_dir, "mr_preprocessor.joblib")
        meta_path = os.path.join(self.mr_dir, "mr_model_metadata.json")

        if not os.path.exists(model_path):
            raise FileNotFoundError(
                f"Phase 15 model not found at {model_path}. "
                "Run POST /api/multiregion/train first to generate it."
            )
        if not os.path.exists(prep_path):
            raise FileNotFoundError(
                f"Phase 15 preprocessor not found at {prep_path}. "
                "Run POST /api/multiregion/train first."
            )

        self.model = joblib.load(model_path)
        self.preprocessor = joblib.load(prep_path)

        # Phase 19: Extract Feature Importances
        if hasattr(self.model, "feature_importances_"):
            importances = self.model.feature_importances_
            # Map them to FEATURE_COLUMNS
            mapped = [
                {"feature": feat, "importance": round(float(imp), 4)}
                for feat, imp in zip(FEATURE_COLUMNS, importances)
            ]
            # Sort by importance descending
            self.feature_importances = sorted(mapped, key=lambda x: x["importance"], reverse=True)
        else:
            self.feature_importances = []

        if os.path.exists(meta_path):
            with open(meta_path) as f:
                self.metadata = json.load(f)

    def is_ready(self) -> bool:
        return self.model is not None and self.preprocessor is not None

    # ------------------------------------------------------------------
    # Region resolution
    # ------------------------------------------------------------------

    def resolve_region(self, lat: float, lon: float) -> Optional[Tuple[str, Dict]]:
        """
        Returns (region_key, region_dict) if (lat, lon) falls inside any
        of the 6 supported manganese belt bounding boxes, else None.

        If a coordinate sits on the border of two bboxes (theoretically
        possible if belts were adjacent), the first match is returned.
        """
        for key, region in MANGANESE_REGIONS.items():
            bbox = region["bbox"]
            if (bbox["lat_min"] <= lat <= bbox["lat_max"] and
                    bbox["lon_min"] <= lon <= bbox["lon_max"]):
                return key, region
        return None

    # ------------------------------------------------------------------
    # Feature synthesis
    # ------------------------------------------------------------------

    def synthesize_features(
        self,
        lat: float,
        lon: float,
        region_key: str,
        region: Dict,
    ) -> pd.DataFrame:
        """
        Builds a single-row feature DataFrame for the Phase 15 model.

        Strategy:
          1. Compute Haversine distance from (lat, lon) to each known deposit
          2. Derive prospectivity label from the nearest-deposit distance
             (same thresholds as training: ≤5 km → High, ≤15 km → Medium, else Low)
          3. Look up region-calibrated median spectral values for that label
          4. Look up terrain medians for that label

        This gives **deterministic, geology-grounded** features rather than
        random values, consistent with the Phase 15 training methodology.
        """
        deposits = region["known_deposits"]
        dep_lats = np.array([d["lat"] for d in deposits])
        dep_lons = np.array([d["lon"] for d in deposits])

        distances = _haversine(lat, lon, dep_lats, dep_lons)
        min_dist = float(np.min(distances))
        nearest_deposit_idx = int(np.argmin(distances))
        label = _proximity_label(min_dist)

        spectral = _SPECTRAL_MEDIANS[label]
        terrain = _TERRAIN_MEDIANS[label]

        row = {
            "elevation": terrain["elevation"],
            "slope":     terrain["slope"],
            **spectral,
        }
        # Ensure column order matches training
        df = pd.DataFrame([{col: row[col] for col in FEATURE_COLUMNS}])
        return df, label, min_dist, nearest_deposit_idx

    # ------------------------------------------------------------------
    # Prediction
    # ------------------------------------------------------------------

    def predict(self, lat: float, lon: float) -> Dict[str, Any]:
        """
        Full prediction pipeline for a given (lat, lon) coordinate.

        Returns a structured dict suitable for the API response.
        Coordinates outside all 6 supported regions return
        is_validated_region=False with a clear explanation — no exception.
        """
        resolution = self.resolve_region(lat, lon)

        # Build list of supported regions for transparency
        supported_regions = [
            {
                "key": k,
                "name": v["name"],
                "state": v["state"],
                "bbox": v["bbox"],
            }
            for k, v in MANGANESE_REGIONS.items()
        ]

        if resolution is None:
            return {
                "latitude": lat,
                "longitude": lon,
                "is_validated_region": False,
                "region_key": None,
                "region_name": None,
                "state": None,
                "geological_note": None,
                "prediction_label": None,
                "prospectivity_score": None,
                "probabilities": None,
                "nearest_deposit_name": None,
                "nearest_deposit_dist_km": None,
                "explainability": None,
                "model_phase": "Phase 15 – Multi-Region RF",
                "data_source": "Region-calibrated feature synthesis (not live satellite imagery)",
                "disclaimer": _DISCLAIMER,
                "message": (
                    "The selected coordinate is outside all 6 supported Indian "
                    "manganese belt regions. Prediction cannot be made. "
                    "Supported regions are listed in 'regions_supported'."
                ),
                "regions_supported": supported_regions,
            }

        region_key, region = resolution

        features_df, inferred_label, min_dist, nearest_idx = self.synthesize_features(
            lat, lon, region_key, region
        )

        # Apply the Phase 15 preprocessor and predict
        X_scaled = self.preprocessor.transform(features_df)
        prediction = self.model.predict(X_scaled)[0]
        proba = self.model.predict_proba(X_scaled)[0]
        class_labels = list(self.model.classes_)
        probabilities = {label: round(float(p), 4) for label, p in zip(class_labels, proba)}

        # Prospectivity score: weighted sum High=1.0, Medium=0.5, Low=0.1
        score = (
            probabilities.get("High", 0) * 1.0
            + probabilities.get("Medium", 0) * 0.5
            + probabilities.get("Low", 0) * 0.1
        )

        nearest_deposit = region["known_deposits"][nearest_idx]

        return {
            "latitude": lat,
            "longitude": lon,
            "is_validated_region": True,
            "region_key": region_key,
            "region_name": region["name"],
            "state": region["state"],
            "geological_note": region["geological_note"],
            "prediction_label": str(prediction),
            "prospectivity_score": round(score, 3),
            "priority": str(prediction),
            "probabilities": probabilities,
            "inferred_proximity_label": inferred_label,
            "nearest_deposit_name": nearest_deposit.get("name"),
            "nearest_deposit_dist_km": round(min_dist, 2),
            "explainability": {
                "feature_importance": self.feature_importances,
                "input_features": features_df.iloc[0].to_dict()
            },
            "model_phase": "Phase 15 – Multi-Region RF",
            "n_training_regions": len(MANGANESE_REGIONS),
            "data_source": (
                "Region-calibrated spectral medians (not live satellite imagery). "
                "Proximity to known deposits determines the feature class."
            ),
            "disclaimer": _DISCLAIMER,
            "message": (
                f"Prediction generated for {region['name']}. "
                f"Nearest known deposit ({nearest_deposit.get('name', 'Unknown')}) "
                f"is {round(min_dist, 1)} km away. "
                f"Inferred prospectivity class from proximity: {inferred_label}."
            ),
            "regions_supported": supported_regions,
        }


# ---------------------------------------------------------------------------
# Convenience functions
# ---------------------------------------------------------------------------

def get_supported_regions() -> List[Dict[str, Any]]:
    """Returns the list of supported regions with metadata (no model needed)."""
    return [
        {
            "key": k,
            "name": v["name"],
            "state": v["state"],
            "bbox": v["bbox"],
            "geological_note": v["geological_note"],
            "n_known_deposits": len(v["known_deposits"]),
        }
        for k, v in MANGANESE_REGIONS.items()
    ]
